### PR TITLE
[PLT-436] - include checkmarx integration

### PR DESCRIPTION
**Pull request by gritzkoo**
- feat: include checkmarx script:
- fix: SC2063 – ShellCheck Wiki
- :zap: fixed sh script to create branch
- chore: fixing checkmarx scripts and steps
- fix: https://www.shellcheck.net/wiki/SC2028 -- echo may not expand escape sequen...   https://www.shellcheck.net/wiki/SC2185 -- Some finds don't have a default p...   https://www.shellcheck.net/wiki/SC2129 -- Consider using { cmd1; cmd2; } >>..
- chore: update scripts
- fix: https://www.shellcheck.net/wiki/SC2145 -- Argument mixes string and array. ...   https://www.shellcheck.net/wiki/SC2076 -- Remove quotes from right-hand sid...   https://www.shellcheck.net/wiki/SC2162 -- read without -r will mangle backs...
- fix:  https://www.shellcheck.net/wiki/SC2076
- chore: fix checkmarx job definition

# PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

The current orb definition does not execute checkmarx scans

Issue Number: `PLT-436`

## The new version

New release version candidate: `v2.0.0`

>Reviewers, please check if the release candidate is present in the changes of this PR in the examples section!

## What is the new behavior?

Now the orb can use the `dft/checkmarx` to scan using default configurations and environments of the circleci
to scan projects

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This release is a feature inclusion and the minor version will be updated to `2.0.0`

### CODE REVIEW

**Review by caykemanjanelli — DISMISSED** [review]
Ok

**Review by gritzkoo — COMMENTED** [review]
reviewd

**Review by caykemanjanelli — APPROVED** [review]
ok

**Review by dioculos — DISMISSED** [review]
LGTM!

**Review by gritzkoo — COMMENTED** [review]
LGTM

**Review by caykemanjanelli — APPROVED** [review]

**Review by caykemanjanelli — APPROVED** [review]

**Review by dioculos — APPROVED** [review]
LGTM!

**Pull request merged**
